# Generated by Django 5.0.2 on 2024-03-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_alter_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created',)},
        ),
    ]
